package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"

	graphqlgen "gobase/graphql/generated"
	productdto "gobase/internal/domain/product/dto"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input productdto.CreateProductInput) (*productdto.Product, error) {
	return r.GraphQLResolver.Product.Create(ctx, input)
}

// CreateProductAttribute is the resolver for the createProductAttribute field.
func (r *mutationResolver) CreateProductAttribute(ctx context.Context, input productdto.CreateProductAttributeInput) (*productdto.ProductAttribute, error) {
	return r.GraphQLResolver.Product.CreateAttribute(ctx, input)
}

// Mutation returns graphqlgen.MutationResolver implementation.
func (r *Resolver) Mutation() graphqlgen.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
